name = "PaveUnpaved's Server Modpack"
author = "PaveUnpaved"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cdc1f86ed29b818d571db87c80a1b1247249959bde3a22b3e84823b0bf62022"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
