name = "PaveUnpaved's Server Modpack"
author = "PaveUnpaved"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a54f503fd807f30047656b4d3cd6d4b7f30313840c22a8e2f920611a1ffed059"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
