name = "PaveUnpaved's Server Modpack"
author = "PaveUnpaved"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06b86f00a56c65be3a512b93c48c26ca24c87db2d61bdeb1acfed613c25a853a"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
